language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7" # see https://github.com/travis-ci/travis-ci/issues/9815
  - "nightly"
  - "pypy"
  - "pypy3"

install:
  - pip install pytest pytest-cov codecov

script:
  - pytest --cov=sqlparse

after_success:
    - codecov
